title: Academy Real Estate Training
author:
  name: Harcourts Academy
  email: 'academy@harcourts.net'
metadata:
    description: 'Grav is an easy to use, yet powerful, open source flat-file CMS'
    
taxonomies: [category,tag]

