# Localhost

cache:
  enabled: false
  gzip: false

twig:
  cache: false
  debug: true

assets:
  css_pipeline: false
  css_minify: false
  js_pipeline: false
  js_minify: false

debugger:
  enabled: true
  twig: true
  shutdown:
    close_connection: false

images:
  default_image_quality: 90
  cache_all: false

analytics:
  enabled: true
  url: //www.academyrealestatetraining.com/webstats/
  siteid: 8
